version: 2.1 

workflows: 
  first-workflow:
    jobs:
      - first-job

jobs:
  first-job:
    docker: 
      - image: cimg/openjdk:21.0.0
    steps:  
      - checkout 
      - run: mkdir test-reports 
      - run: mvn dependency:resolve      
      - run: 
          name: Run specific tests
          command: mvn clean test -Psmoke
        
